components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Access Token을 입력해주세요.
tags:
  - name: Auth
    description: 사용자 인증 및 권한
  - name: User
    description: 사원 개인 정보 및 계정 관리
  - name: Dashboard
    description: 전체 통계 및 요약 정보 조회
  - name: Image
    description: 이미지 업로드 및 URL 생성 관리
  - name: Company
    description: 회사 정보 및 소속 사원 관리 (관리자 권한)
  - name: Car
    description: 차량 등록, 수정 및 모델 목록 관리
  - name: Customer
    description: 고객 정보 등록 및 대용량 데이터 관리
  - name: Contract
    description: 차량/고객/유저 기반 계약 정보 관리
  - name: ContractDocument
    description: 계약서 업로드, 다운로드 및 관련 서류 관리